language: r
cache: packages
sudo: false

matrix:
  include:
    - os: linux
      r: release
    
    - os: linux
      r: devel

    - os: osx
      r: devel

r_packages:
- Rcpp
- RcppArmadillo
- landpred
- MASS

r_check_args: "--as-cran --timings"
