// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// dnormC_multi
NumericMatrix dnormC_multi(NumericVector x, NumericVector m, double sd, bool Log);
RcppExport SEXP sslcov_dnormC_multi(SEXP xSEXP, SEXP mSEXP, SEXP sdSEXP, SEXP LogSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type sd(sdSEXP);
    Rcpp::traits::input_parameter< bool >::type Log(LogSEXP);
    __result = Rcpp::wrap(dnormC_multi(x, m, sd, Log));
    return __result;
END_RCPP
}
// ecdf_cpp
NumericVector ecdf_cpp(NumericVector sobs, NumericVector sref);
RcppExport SEXP sslcov_ecdf_cpp(SEXP sobsSEXP, SEXP srefSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type sobs(sobsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sref(srefSEXP);
    __result = Rcpp::wrap(ecdf_cpp(sobs, sref));
    return __result;
END_RCPP
}
