# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' C++ implementation of univariate Normal of mean zero pdf for multiple inputs
#'
#'@param x vector of inputs
#'@param m vector of means
#'@param sd the standard deviation
#'@param Log logical flag for returning the log of the probability density
#'function. Defaults is \code{TRUE}
#'@return matrix of densities of dimension \code{p x n}.
#'@export
dnormC_multi <- function(x, m, sd, Log = FALSE) {
    .Call('sslcov_dnormC_multi', PACKAGE = 'sslcov', x, m, sd, Log)
}

#'C++ implementation of empirical cdf
#'
#'@param sobs the observation for which the cdf is to be evaluated
#'
#'@param sref the reference observations from which the cdf is to be constructed
#'
#'@useDynLib sslcov
#'@examples
#'library(microbenchmark)
#'fi <- rnorm(n=1000)
#'n_new <- 100
#'fnew <- rnorm(n=n_new) 
#'microbenchmark(#sum.I(c(fi, fnew), FUN=">=", fnew)/n_new,
#'    ecdf(fnew)(c(fi, fnew)),
#'    ecdf_cpp(c(fi, fnew), sort(fnew))/n_new
#')
#'@export
ecdf_cpp <- function(sobs, sref) {
    .Call('sslcov_ecdf_cpp', PACKAGE = 'sslcov', sobs, sref)
}

